In [1]:
import tensorflow as tf
x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y + 2

In [10]:
sess = tf.compat.v1.Session()

In [12]:
sess.close()

In [2]:
import tensorflow as tf
graph = tf.Graph()
with graph.as_default():
    x2 = tf.Variable(2)
x2.graph is graph

True

In [3]:
x2.graph is tf.get_default_graph()

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

In [6]:
w = tf.constant(3)
x = w + 2
y = x + 5
z = x * 3
with tf.compat.v1.Session() as sess:
    print(y)
    print(z.eval())

tf.Tensor(10, shape=(), dtype=int32)


NotImplementedError: eval is not supported when eager execution is enabled, is .numpy() what you're looking for?

In [11]:
import numpy as np
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

x = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="x")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
xt = tf.transpose(x)
theta = tf.matmul(tf.matmul(tf.linalg.inv(tf.matmul(xt,x)), xt), y)

theta

<tf.Tensor: shape=(9, 1), dtype=float32, numpy=
array([[-3.68272896e+01],
       [ 4.36930180e-01],
       [ 9.45575722e-03],
       [-1.07554615e-01],
       [ 6.45712018e-01],
       [-3.88248327e-06],
       [-3.78954294e-03],
       [-4.20148313e-01],
       [-4.33188230e-01]], dtype=float32)>

In [74]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

n_epochs = 1000
learning_rate = 0.0000001

x = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="x")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random.uniform([n + 1, 1], -1.0, 1.0), name="theta")

for epoch in range(n_epochs):
    if epoch % 100 == 0:
        y_pred = tf.matmul(x, theta, name="predictions")
        error = y_pred - y
        mse = tf.reduce_mean(tf.square(error), name="mse")
        gradients = 2/m * tf.matmul(tf.transpose(x), error)
        theta.assign(theta - learning_rate * gradients)
        print("Epoch", epoch, "MSE=", mse)
print(theta)

Epoch 0 MSE= tf.Tensor(2022608.4, shape=(), dtype=float32)
Epoch 100 MSE= tf.Tensor(233528.7, shape=(), dtype=float32)
Epoch 200 MSE= tf.Tensor(32580.26, shape=(), dtype=float32)
Epoch 300 MSE= tf.Tensor(9995.309, shape=(), dtype=float32)
Epoch 400 MSE= tf.Tensor(7442.4404, shape=(), dtype=float32)
Epoch 500 MSE= tf.Tensor(7139.4233, shape=(), dtype=float32)
Epoch 600 MSE= tf.Tensor(7089.129, shape=(), dtype=float32)
Epoch 700 MSE= tf.Tensor(7067.2603, shape=(), dtype=float32)
Epoch 800 MSE= tf.Tensor(7048.627, shape=(), dtype=float32)
Epoch 900 MSE= tf.Tensor(7030.3984, shape=(), dtype=float32)
<tf.Variable 'theta:0' shape=(9, 1) dtype=float32, numpy=
array([[-0.18786396],
       [ 0.48274758],
       [-0.29387924],
       [-0.1791559 ],
       [ 0.60482407],
       [ 0.05681542],
       [-0.7180897 ],
       [-0.7577709 ],
       [ 0.78878653]], dtype=float32)>


In [48]:
from datetime import datetime

now = datetime.utcnow().strftime("%y%m%d%H%M%S")
root_logdir = "tf_logs"
log_dir = "{}/run-{}/"

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=100.0>